/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mobile_android_myapplication_MathKit */

#ifndef _Included_mobile_android_myapplication_MyNDK
#define _Included_mobile_android_myapplication_MathKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mobile_android_myapplication_MyNDK
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_universe_android_mobile_ndkdemo_MyNDK_square
  (JNIEnv *, jclass, jint);

/*
 * Class:     mobile_android_myapplication_MyNDK
 * Method:    jc
 * Signature: ()J
 */

JNIEXPORT jlong JNICALL Java_universe_android_mobile_ndkdemo_MyNDK_jc
        (JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif
#endif
